project:
  type: website
  output-dir: docs

resources:
  - "exercises/*"
  - "extra/*"

execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Introduction to Bayesian Statistics"
  navbar:
    left:
      - href: index.qmd
        text: home
    right:
      - icon: github
        href: https://github.com/stat-teaching/intro-bayesian-statistics-bertinoro
        aria-label: GitHub
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
